name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start API services
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python src/main.py &
        python data_collection/server/app.py &
        sleep 10

    - name: Test API endpoints
      run: |
        curl -f http://127.0.0.1:5000/ || exit 1
        curl -f http://127.0.0.1:5000/about || exit 1
        curl -f http://127.0.0.1:5000/batches || exit 1
        curl -f http://127.0.0.1:5000/galleries || exit 1
        curl -f http://127.0.0.1:5000/check-directories || exit 1
        curl -f http://127.0.0.1:5000/galleries/registered || exit 1
        curl -f http://127.0.0.1:5000/database/stats || exit 1
        curl -f http://127.0.0.1:5000/api/collection-app-status || exit 1
        curl -f http://127.0.0.1:5000/api/collection-app-config || exit 1
        curl -f http://127.0.0.1:5000/student-data/folders || exit 1
        curl -f http://127.0.0.1:5000/api/admins || exit 1
        curl -f http://127.0.0.1:8001/ || exit 1
        curl -f http://127.0.0.1:8001/api/batches || exit 1
        curl -f http://127.0.0.1:8001/qr || exit 1
        curl -f http://127.0.0.1:8001/about || exit 1
    - name: Stop API services
      run: |
        pkill -f "python src/main.py"
        pkill -f "python data_collection/server/app.py"

    - name: Test executable scripts
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python scripts/create_superadmin.py --help
